FROM node:20-alpine AS build

WORKDIR /app

ARG NODE_ENV=production
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GA_ID
ARG NEXT_PUBLIC_META_PIXEL_ID
ARG NEXT_PUBLIC_RAYAPP_COMPANY_ID
ARG NEXT_PUBLIC_SITE_URL
ARG RAYAPP_API_BASE_URL
ARG RAYAPP_COMPANY_ID
ARG RAYAPP_COMPANY_NAME
ARG N8N_WEBHOOK_URL

ENV NODE_ENV=$NODE_ENV
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_GA_ID=$NEXT_PUBLIC_GA_ID
ENV NEXT_PUBLIC_META_PIXEL_ID=$NEXT_PUBLIC_META_PIXEL_ID
ENV NEXT_PUBLIC_RAYAPP_COMPANY_ID=$NEXT_PUBLIC_RAYAPP_COMPANY_ID
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://feriadovermu.com}
ENV RAYAPP_API_BASE_URL=$RAYAPP_API_BASE_URL
ENV RAYAPP_COMPANY_ID=$RAYAPP_COMPANY_ID
ENV RAYAPP_COMPANY_NAME=$RAYAPP_COMPANY_NAME
ENV N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL

COPY package*.json ./
# aquí SÍ instalamos devDependencies para compilar
RUN npm install --legacy-peer-deps --include=dev

COPY . .
RUN npm run build

# Runtime (solo prod deps)
FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=build /app/package*.json ./
RUN npm install --legacy-peer-deps --omit=dev

COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public

EXPOSE 3000
CMD ["npm","run","start"]