apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feriado-preprod-ingress
  namespace: feriado
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "http-to-https-redirect"
    networking.gke.io/managed-certificates: "feriado-preprod-managed-cert" # Define the ManagedCertificate name
spec:
  rules:
  # Regla para el host de preproducción de Feriado Cantina
  - host: feriado.preprod.rayapp.io
    http:
      paths:
      # Ruta por defecto para todo el tráfico en este host (frontend)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: feriado-service
            port:
              number: 80 # Asegúrate de que sea el puerto correcto de tu servicio frontend para el Ingress
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  annotations:
  name: feriado-preprod-managed-cert
  namespace: feriado
spec:
  domains:
  - feriado.preprod.rayapp.io
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https-redirect
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
